name: Loclio
favicon: null
layout_spectrum: 0.14506410527974367
typography_spectrum: 0.3825893097091466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7650446351617575
  lightness: 0.3299269028939307
  saturation: 0.3441374930553138
  rhythmicContrast: 0.7381577414926142
purpose: []
